M48
; DRILL file {KiCad 9.0.0} date 2025-03-14T14:40:56+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-14T14:40:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X112.53Y-93.075
X112.53Y-97.925
T2
X109.5Y-92.775
X109.5Y-98.225
T3
X118.1Y-91.9
X173.9Y-83.6
X178.6Y-100.9
M30
